<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="yashodhar-Lenovo-ideapad-300-15ISK" tests="1" failures="1" timestamp="11 Dec 2017 20:00:25 GMT" time="0.068" errors="0">
  <testcase name="testSalutationMessage" time="0.013" classname="UnitTest">
    <failure type="java.lang.AssertionError" message="expected [dfasfas] but found [Hi!Manisha]">
      <![CDATA[java.lang.AssertionError: expected [dfasfas] but found [Hi!Manisha]
	at UnitTest.testSalutationMessage(UnitTest.java:14)
	at org.scalatest.testng.TestNGSuiteLike.run(TestNGSuiteLike.scala:261)
	at org.scalatest.testng.TestNGSuiteLike.run$(TestNGSuiteLike.scala:254)
	at org.scalatest.testng.TestNGSuite.run(TestNGSuite.scala:67)
	at org.scalatest.testng.TestNGSuiteLike.runTestNG(TestNGSuiteLike.scala:248)
	at org.scalatest.testng.TestNGSuiteLike.runTestNG$(TestNGSuiteLike.scala:227)
	at org.scalatest.testng.TestNGSuite.runTestNG(TestNGSuite.scala:67)
	at org.scalatest.testng.TestNGSuiteLike.run(TestNGSuiteLike.scala:149)
	at org.scalatest.testng.TestNGSuiteLike.run$(TestNGSuiteLike.scala:146)
	at org.scalatest.testng.TestNGSuite.run(TestNGSuite.scala:67)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testSalutationMessage -->
</testsuite>
